# -*- coding: utf-8 -*-
"""multi-function calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yu4r1CXczgFOEDNwVxoGXegOAUe2fHGf
"""

from fractions import Fraction
import sympy as sp
def multi_function_Calculator():
  print("Welcome to the Muti_Function_Calculator")

def solve_proportion(a, b, c):
    """Solves for x in a proportion a/b = c/x."""

    x = (b * c) / a
    return x

def solve_for_x(equation, variable):
    """Solves for x in an algebraic equation."""
    x = sp.Symbol(variable)
    solution = sp.solve(equation, x)
    return solution

def factor_square_root(n):
    """Factors a square root."""
    return sp.factor(sp.sqrt(n))

def decimal_to_fraction(decimal):
    """Converts a decimal to a fraction."""
    return Fraction(decimal).limit_denominator()

def decimal_to_percent(decimal):
    """Converts a decimal to a percent."""
    return decimal * 100

def fraction_to_decimal(fraction):
    """Converts a fraction to a decimal."""
    return float(Fraction(fraction))

def fraction_to_percent(fraction):
    """Converts a fraction to a percent."""
    return float(Fraction(fraction)) * 100

def percent_to_decimal(percent):
    """Converts a percent to a decimal."""
    return percent / 100

def percent_to_fraction(percent):
    """Converts a percent to a fraction."""
    return Fraction(percent, 100).limit_denominator()

# # Example Usage
print("Solving proportion 3/4 = 9/x:", solve_proportion(3, 4, 9))
# print("Solving equation x + 2 = 5 for x:", solve_for_x("x + 2 - 5", "x"))
# print("Factoring square root of 50:", factor_square_root(50))
# print("Converting decimal 0.75 to fraction:", decimal_to_fraction(0.75))
# print("Converting decimal 0.75 to percent:", decimal_to_percent(7.5))
# print("Converting fraction '3/4' to decimal:", fraction_to_decimal("3/4"))
# print("Converting fraction '3/4' to percent:", fraction_to_percent("3/4"))
# print("Converting percent 75 to decimal:", percent_to_decimal(75))
# print("Converting percent 75 to fraction:", percent_to_fraction(75))

def calculator():
  print("Welcome to the Calculator")
  print("1: Solve Proportion")
  print("2: Solve Equation")
  print("3: Factor Square root")
  print("4: Convert Decimal to Fraction")
  print("5: Convert Decimal to Percent")
  print("6: Convert Fraction to Decimal")
  print("7: Convert Fraction to Percent")
  print("8: Convert Percent to Decimal")
  print("9: Convert Percent to Fraction")

  choice=input("Enter the corresponding to your choice: ")

  if choice =="1":
    a=int(input("Enter the first number: "))
    b=int(input("Enter the second number: "))
    c=int(input("Enter the third number: "))
    print("The answer is: ", solve_proportion(a, b, c))
  elif choice =="2":
    equation=input("Enter the equation: ")
    variable=input("Enter the variable: ")
    print("The answer is: ", solve_for_x(equation, variable))
  elif choice =="3":
    n=int(input("Enter the number: "))
    print("The answer is: ", factor_square_root(n))
  elif  choice =="4":
    decimal=float(input("Enter the decimal: "))
    print("The answer is: ", decimal_to_fraction(decimal))
  elif choice =="5":
    decimal=float(input("Enter the decimal: "))
    print("The answer is: ", decimal_to_percent(decimal))
  elif choice =="6":
    fraction=input("Enter the fraction: ")
    print("The answer is: ", fraction_to_decimal(fraction))
  elif choice =="7":
    fraction=input("Enter the fraction: ")
    print("The answer is: ", fraction_to_percent(fraction))
  elif choice =="8":
    percent=float(input("Enter the percent: "))
    print("The answer is: ", percent_to_decimal(percent))
  elif choice =="9":
    percent=float(input("Enter the percent: "))
    print("The answer is: ", percent_to_fraction(percent))
  else:
    print("Invalid choice. Please enter 1 to 9.")
calculator()

